#!/usr/bin/env node

/**
 * This script generates a version.ts file with a timestamp and unique build ID
 * to help with cache busting in the application.
 */

const fs = require('fs');
const path = require('path');

// Create a version object with current timestamp and random build ID
const version = {
  timestamp: new Date().toISOString(),
  buildId: Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15)
};

// Create the content for the version.ts file
const content = `// This file is automatically generated during the build process
// Generated on: ${version.timestamp}
export const VERSION = {
  timestamp: '${version.timestamp}',
  buildId: '${version.buildId}'
};
`;

// Ensure the directory exists
const targetDir = path.resolve(__dirname, '../src');
if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

// Write the version file
const filePath = path.join(targetDir, 'version.ts');
fs.writeFileSync(filePath, content);

console.log(`Version file generated at ${filePath}`);
console.log(`Build ID: ${version.buildId}`);
console.log(`Timestamp: ${version.timestamp}`);
